language: go
go: "1.10"

os: linux
sudo: required
dist: trusty

addons:
  artifacts: true

jobs:
  include:
    - stage: test
      name: "Test and lint gotapdance"
      install:
        - go get -t ./...
        - go get github.com/golang/lint/golint
        - go get github.com/alecthomas/gometalinter
      script:
        - go test -race -v ./tapdance
        - go test -race -v ./tdproxy
        - gometalinter --install
        - gometalinter --disable-all -E vet -E gofmt -E misspell -E ineffassign -E deadcode --tests ./tapdance

    - &build-cli
      stage: build
      name: "Build cli and Psiphon ConsoleClient on Linux"
      install:
        - go get ./...
        - mkdir -p $GOPATH/src/github.com/Psiphon-Labs
        - git clone https://github.com/Psiphon-Labs/psiphon-tunnel-core.git $GOPATH/src/github.com/Psiphon-Labs/psiphon-tunnel-core
        - go get github.com/kardianos/govendor
        - (cd $GOPATH/src/github.com/Psiphon-Labs/psiphon-tunnel-core && govendor remove github.com/sergeyfrolov/gotapdance/...)
        - sed -i -e 's/refraction_networking_tapdance.Logger().Out = ioutil.Discard//' $GOPATH/src/github.com/Psiphon-Labs/psiphon-tunnel-core/psiphon/common/tapdance/tapdance.go
      script:
        - mkdir build
        - go build -o build/cli ./cli
        - go build -o build/ConsoleClient -tags 'TAPDANCE' github.com/Psiphon-Labs/psiphon-tunnel-core/ConsoleClient

    - <<: *build-cli
      name: "Build cli and Psiphon ConsoleClient on OS X"
      os: osx
