language: go

go:
  - "1.11"

addons:
  artifacts: true

install:
  - mkdir -p $GOPATH/src/github.com/Psiphon-Labs
  - git clone https://github.com/Psiphon-Labs/psiphon-tunnel-core.git $GOPATH/src/github.com/Psiphon-Labs/psiphon-tunnel-core
  - go get github.com/kardianos/govendor
  - cd $GOPATH/src/github.com/Psiphon-Labs/psiphon-tunnel-core && govendor remove github.com/sergeyfrolov/gotapdance/...

script:
  - go build -tags 'TAPDANCE' github.com/Psiphon-Labs/psiphon-tunnel-core/ConsoleClient
